//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q0 0 q1
        ///q0 1 q2
        ///q0 2 q2
        ///q0 3 q2
        ///q0 4 q2
        ///q0 5 q2
        ///q0 6 q2
        ///q0 7 q2
        ///q0 8 q2
        ///q0 9 q2
        ///
        ///q2 0 q2
        ///q2 1 q2
        ///q2 2 q2
        ///q2 3 q2
        ///q2 4 q2
        ///q2 5 q2
        ///q2 6 q2
        ///q2 7 q2
        ///q2 8 q2
        ///q2 9 q2
        ///
        ///q1 0 q2
        ///q1 1 q2
        ///q1 2 q2
        ///q1 3 q2
        ///q1 4 q2
        ///q1 5 q2
        ///q1 6 q2
        ///q1 7 q2
        ///q1 8 q2
        ///q1 9 q2
        ///
        ///q1 b q3
        ///q1 B q3
        ///
        ///q3 0 q4
        ///q3 1 q4
        ///
        ///q4 0 q4
        ///q4 1 q4
        ///
        ///q1 x q5
        ///q1 X q5
        ///
        ///q5 0 q6
        ///q5 1 q6
        ///q5 2 q6
        ///q5 3 q6
        ///q5 4 q6
        ///q5 5 q6
        ///q5 6 q6
        ///q5 7 q6
        ///q5 8 q6
        ///q5 9 q6
        ///q5 A q6
        ///q5 B q6
        ///q5 C q6
        ///q5 D q6
        ///q5 E q6
        ///q5 F q6
        ///q5 a q6
        ///q5  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string af_const {
            get {
                return ResourceManager.GetString("af_const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q0 A q1
        ///q0 B q1
        ///q0 C q1
        ///q0 D q1
        ///q0 E q1
        ///q0 F q1
        ///q0 G q1
        ///q0 H q1
        ///q0 I q1
        ///q0 J q1
        ///q0 K q1
        ///q0 L q1
        ///q0 M q1
        ///q0 N q1
        ///q0 O q1
        ///q0 P q1
        ///q0 Q q1
        ///q0 R q1
        ///q0 S q1
        ///q0 T q1
        ///q0 U q1
        ///q0 V q1
        ///q0 W q1
        ///q0 X q1
        ///q0 Y q1
        ///q0 Z q1
        ///q0 a q1
        ///q0 b q1
        ///q0 c q1
        ///q0 d q1
        ///q0 e q1
        ///q0 f q1
        ///q0 g q1
        ///q0 h q1
        ///q0 i q1
        ///q0 j q1
        ///q0 k q1
        ///q0 l q1
        ///q0 m q1
        ///q0 n q1
        ///q0 o q1
        ///q0 p q1
        ///q0 q q1
        ///q0 r q1
        ///q0 s q1
        ///q0 t q1
        ///q0 u q1
        ///q0 v q1
        ///q0 w q1
        ///q0 x q1
        ///q0 y q1
        ///q0 z q1
        ///
        ///q1 0 q1
        ///q1 1 q1
        ///q1 2 q1
        ///q1 3 q1
        ///q1 4 q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string af_id {
            get {
                return ResourceManager.GetString("af_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q0 # q1
        ///q1 i q2
        ///q2 n q3
        ///q3 c q4
        ///q4 l q5
        ///q5 u q6
        ///q6 d q7
        ///q7 e q8.
        /// </summary>
        internal static string af_include {
            get {
                return ResourceManager.GetString("af_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q0 \s q1
        ///q0 \n q1
        ///q0 \t q1
        ///
        ///q0 \r q2
        ///
        ///q2 \n q3
        ///
        ///
        ///#s q0
        ///#f q1 q2 q3.
        /// </summary>
        internal static string af_spaces {
            get {
                return ResourceManager.GetString("af_spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q0 + q1
        ///q0 - q1
        ///q0 * q1
        ///q0 / q1
        ///
        ///q0 &lt; q2
        ///q0 &gt; q2
        ///q0 = q2
        ///
        ///q2 = q3
        ///
        ///q0 ! q4
        ///q4 = q3
        ///
        ///#s q0
        ///#f q1 q2 q3
        ///
        ///.
        /// </summary>
        internal static string af_sym {
            get {
                return ResourceManager.GetString("af_sym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include
        ///iostream
        ///using
        ///namespace
        ///std
        ///int
        ///float
        ///main
        ///return
        ///while
        ///for
        ///if
        ///else
        ///cin
        ///cout
        ///endl.
        /// </summary>
        internal static string rKeyWords {
            get {
                return ResourceManager.GetString("rKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +
        ///-
        ///*
        ////
        ///%
        ///=
        ///&lt;
        ///&gt;
        ///==
        ///!=
        ///&lt;=
        ///&gt;=
        ///&lt;&lt;
        ///&gt;&gt;
        ///(
        ///)
        ///{
        ///}
        ///;
        ///,
        ///.
        /// </summary>
        internal static string rSymbols {
            get {
                return ResourceManager.GetString("rSymbols", resourceCulture);
            }
        }
    }
}
