-- DIRTY READS

SELECT * FROM Profesori

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- solutia : READ COMMITED
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT2 : SELECTING 1'
SELECT * FROM Profesori WHERE Pid=2
WAITFOR DELAY '00:00:10'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT2 : SELECTING 2'
SELECT * FROM Profesori WHERE Pid=2
COMMIT TRAN