-- DIRTY READS


BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT1 : UPDATING'
UPDATE Profesori SET Nume='Balcescu' WHERE Pid=2
WAITFOR DELAY '00:00:10'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT1 : CANCELLING'
ROLLBACK TRAN