USE DepozitColectie;
GO

-- DIRTY READS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT2 : SELECTING 1'
SELECT * FROM TitluJocVideo WHERE IdTitluJocVideo=1
WAITFOR DELAY '00:00:7'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT2 : SELECTING 2'
SELECT * FROM TitluJocVideo WHERE IdTitluJocVideo=1
COMMIT TRAN

-- NON-REPEATABLE READS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' NRR2 : SELECTING 1'
SELECT * FROM TitluJocVideo WHERE IdTitluJocVideo=1
WAITFOR DELAY '00:00:7'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' NRR2 : SELECTING 2'
SELECT * FROM TitluJocVideo WHERE IdTitluJocVideo=1
COMMIT TRAN


-- PHANTOM READS
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' PR2 : SELECTING 1'
SELECT * FROM TitluJocVideo 
WAITFOR DELAY '00:00:7'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' PR2 : SELECTING 2'
SELECT * FROM TitluJocVideo
COMMIT TRAN

-- DEADLOCK


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRY
	BEGIN TRAN
	UPDATE TitluJocVideo SET CopiiVandute=33 WHERE IdTitluJocVideo=1;
	WAITFOR DELAY '00:00:10'
	UPDATE ExemplarJocVideo SET StareConservare=3 WHERE IdExemplarJocVideo=2;
	COMMIT TRAN
	SELECT 'OK' AS MSG;  
END TRY BEGIN CATCH
	SELECT ERROR_MESSAGE() AS MSG;  
END CATCH

GO

CREATE OR ALTER PROCEDURE DeadLock2 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	BEGIN TRY
		BEGIN TRAN
		UPDATE TitluJocVideo SET CopiiVandute=33 WHERE IdTitluJocVideo=1;
		WAITFOR DELAY '00:00:10'
		UPDATE ExemplarJocVideo SET StareConservare=3 WHERE IdExemplarJocVideo=2;
		COMMIT TRAN
		SELECT 'OK' AS MSG;  
	END TRY BEGIN CATCH
		SELECT ERROR_MESSAGE() AS MSG;  
	END CATCH
END
GO