USE DepozitColectie;

UPDATE TitluJocVideo SET CopiiVandute=0 WHERE IdTitluJocVideo = 1
DELETE FROM TitluJocVideo WHERE Nume='Test Game'
SELECT * FROM TitluJocVideo


-- DIRTY READS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- >> READ COMMITED
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT1 : UPDATING'
UPDATE TitluJocVideo SET CopiiVandute=15 WHERE IdTitluJocVideo = 1
WAITFOR DELAY '00:00:10'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' DT1 : CANCELLING'
ROLLBACK TRAN

-- NON-REPEATABLE READS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED -- >> REPPEATABLE READ
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' NRR1 : STARTING'
WAITFOR DELAY '00:00:10'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' NRR1 : UPDATING'
UPDATE TitluJocVideo SET CopiiVandute=15 WHERE IdTitluJocVideo = 1
COMMIT TRAN

-- PHANTOM READS
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- SERIALIZABLE
BEGIN TRAN
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' PR1 : STARTING'
WAITFOR DELAY '00:00:10'
PRINT CAST(SYSDATETIME() AS VARCHAR)+ ' PR1 : INSERTING'
INSERT INTO TitluJocVideo (Nume, Platforma, DataLansare) VALUES ('Test Game', 1, '2023-01-01')
COMMIT TRAN

-- DEADLOCK

SET DEADLOCK_PRIORITY HIGH
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
UPDATE ExemplarJocVideo SET StareConservare=7 WHERE IdExemplarJocVideo=2;
WAITFOR DELAY '00:00:10'
UPDATE TitluJocVideo SET CopiiVandute=23 WHERE IdTitluJocVideo=1;
COMMIT TRAN

GO

CREATE OR ALTER PROCEDURE DeadLock1 AS
BEGIN
	SET DEADLOCK_PRIORITY HIGH
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	BEGIN TRY		
		BEGIN TRAN
		UPDATE ExemplarJocVideo SET StareConservare=7 WHERE IdExemplarJocVideo=2;
		WAITFOR DELAY '00:00:10'
		UPDATE TitluJocVideo SET CopiiVandute=23 WHERE IdTitluJocVideo=1;
		COMMIT TRAN
		SELECT 'OK' AS MSG;  
	END TRY BEGIN CATCH
		SELECT ERROR_MESSAGE() AS MSG; 
	END CATCH
END
GO
