//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI.Lab11.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI.Lab11.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emoji16_img {
            get {
                object obj = ResourceManager.GetObject("emoji16_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emoji32_img {
            get {
                object obj = ResourceManager.GetObject("emoji32_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HASH_KEY 0 0
        ///KEYCAP:_* 0 1
        ///KEYCAP_0 0 2
        ///KEYCAP_1 0 3
        ///KEYCAP_2 0 4
        ///KEYCAP_3 0 5
        ///KEYCAP_4 0 6
        ///KEYCAP_5 0 7
        ///KEYCAP_6 0 8
        ///KEYCAP_7 0 9
        ///KEYCAP_8 0 10
        ///KEYCAP_9 0 11
        ///COPYRIGHT_SIGN 0 12
        ///REGISTERED_SIGN 0 13
        ///MAHJONG_TILE_RED_DRAGON 0 14
        ///PLAYING_CARD_BLACK_JOKER 0 15
        ///NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_A 0 16
        ///NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_B 0 17
        ///NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_O 0 18
        ///NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_P 0 19
        ///NEGATIVE_SQUARED_AB 0 20
        ///SQUARED_CL 0 21
        ///SQUARED_COOL 0 22
        ///SQUARED_FREE 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoji32_txt {
            get {
                return ResourceManager.GetString("emoji32_txt", resourceCulture);
            }
        }
    }
}
