//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabCDiezFacultativ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabCDiezFacultativ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoala Gimnaziala “Horea”;Houston Rockets
        ///Scoala Gimnaziala &quot;Octavian Goga&quot;;Los Angeles Lakers
        ///Liceul Teoretic &quot;Lucian Blaga&quot;;LA Clippers
        ///Scoala Gimnaziala &quot;Ioan Bob&quot;;Chicago Bulls
        ///Scoala Gimnaziala &quot;Ion Creanga&quot;;Cleveland Cavaliers
        ///Colegiul National Pedagogic &quot;Gheorghe Lazar&quot;;UtahJazz
        ///Scoala Gimnaziala Internationala SPECTRUM;Brooklyn Nets
        ///Colegiul National „Emil Racovita”;New Orleans Pelicans
        ///Colegiul National &quot;George Cosbuc&quot;;Indiana Pacers
        ///Scoala Gimnaziala &quot;Ion Agarbiceanu&quot;;Toronto Raptors
        ///Liceul Teoret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string echipe {
            get {
                return ResourceManager.GetString("echipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abel
        ///Achim
        ///Adam
        ///Adela
        ///Adelaida
        ///Adelin
        ///Adelina
        ///Adina
        ///Adnana
        ///Adonis
        ///Adrian
        ///Adriana
        ///Agata
        ///Aglaia
        ///Agnos
        ///Agripina
        ///Aida
        ///Albert
        ///Alberta
        ///Albertina
        ///Aleodor
        ///Alex
        ///Alexandra
        ///Alexandrina
        ///Alexandru
        ///Alexe
        ///Alexia
        ///Alice
        ///Alida
        ///Alin
        ///Alina
        ///Alis
        ///Alistar
        ///Alma
        ///Amalia
        ///Amanda
        ///Amedeu
        ///Amelia
        ///Amza
        ///Anabela
        ///Anaida
        ///Anamaria
        ///Anastasia
        ///Anatolie
        ///Anca
        ///Ancuța
        ///Anda
        ///Andra
        ///Andrada
        ///Andreea
        ///Andrei
        ///Andrian
        ///Anemona
        ///Aneta
        ///Angel
        ///Angela
        ///Angelica
        ///Anghel
        ///Anghelina
        ///Anica
        ///Anișoara
        ///Antim
        ///Antoaneta
        ///Anton
        ///Antonela
        ///Antonia
        ///Antonie
        ///Antoniu
        ///Anuța
        ///Arcadian
        ///Ariadn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fnames {
            get {
                return ResourceManager.GetString("fnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaftenei
        ///Aalboaiei
        ///Aalexoaiei
        ///Aamzăr
        ///Aancuței
        ///Aandriesei
        ///Aanei
        ///Aanicăi
        ///Aanii
        ///Aaniței
        ///Aanuței
        ///Aaron
        ///Aaxiniei
        ///Ababe
        ///Ababei
        ///Ababi
        ///Ababie
        ///Ababii
        ///Abadi
        ///Abadii
        ///Abageriu
        ///Abageru
        ///Abagiu
        ///Abandei
        ///Abaza
        ///Abdulea
        ///Abeaboeru
        ///Abeaboieru
        ///Abejenoaiei
        ///Abel
        ///Abela
        ///Abercei
        ///Abetegi
        ///Abetegii
        ///Abiculesei
        ///Abiculesi
        ///Abitănci
        ///Abiței
        ///Ablachim
        ///Ablai
        ///Aboaice
        ///Aboboaie
        ///Abobului
        ///Abogătoae
        ///Abogătoaie
        ///Abonculesei
        ///Abordeoaei
        ///Abordiencei
        ///Abordioaei
        ///Aborșoaie
        ///Abostănoae
        ///Abouriței
        ///Aboș
        ///Aboșculesi
        ///Abraham
        ///Abram
        ///Abramciuc
        ///Abramiuc
        ///Abramovici
        ///Abrașu
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lnames {
            get {
                return ResourceManager.GetString("lnames", resourceCulture);
            }
        }
    }
}
