//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI.Lab4Opt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI.Lab4Opt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] aves_sparrow_social {
            get {
                object obj = ResourceManager.GetObject("aves_sparrow_social", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;http://networkrepository.com/assets/css/bootstrap.css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/responsive.css&quot;&gt;   
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/style.css&quot;&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///&lt;div class=&quot;row&quot;&gt;
        ///&lt;div class=&quot;col-md-12&quot;&gt;
        ///&lt;div class=&quot;panel panel-success&quot;&gt;
        ///    &lt;div class=&quot;panel-heading&quot;&gt;
        ///        &lt;h3 class=&quot;panel-title&quot;&gt;&lt;i class=&quot;icon-group icon-large&quot;&gt;&lt;/i&gt; Acknowledgement  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aves_sparrow_social1 {
            get {
                return ResourceManager.GetString("aves_sparrow_social1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] insecta_ant_trophallaxis_colony2 {
            get {
                object obj = ResourceManager.GetObject("insecta_ant_trophallaxis_colony2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;http://networkrepository.com/assets/css/bootstrap.css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/responsive.css&quot;&gt;   
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/style.css&quot;&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///&lt;div class=&quot;row&quot;&gt;
        ///&lt;div class=&quot;col-md-12&quot;&gt;
        ///&lt;div class=&quot;panel panel-success&quot;&gt;
        ///    &lt;div class=&quot;panel-heading&quot;&gt;
        ///        &lt;h3 class=&quot;panel-title&quot;&gt;&lt;i class=&quot;icon-group icon-large&quot;&gt;&lt;/i&gt; Acknowledgement  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insecta_ant_trophallaxis_colony21 {
            get {
                return ResourceManager.GetString("insecta_ant_trophallaxis_colony21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mammalia_raccoon_proximity {
            get {
                object obj = ResourceManager.GetObject("mammalia_raccoon_proximity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;http://networkrepository.com/assets/css/bootstrap.css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/responsive.css&quot;&gt;   
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/style.css&quot;&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///&lt;div class=&quot;row&quot;&gt;
        ///&lt;div class=&quot;col-md-12&quot;&gt;
        ///&lt;div class=&quot;panel panel-success&quot;&gt;
        ///    &lt;div class=&quot;panel-heading&quot;&gt;
        ///        &lt;h3 class=&quot;panel-title&quot;&gt;&lt;i class=&quot;icon-group icon-large&quot;&gt;&lt;/i&gt; Acknowledgement  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mammalia_raccoon_proximity1 {
            get {
                return ResourceManager.GetString("mammalia_raccoon_proximity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] reptilia_tortoise_network_hw {
            get {
                object obj = ResourceManager.GetObject("reptilia_tortoise_network_hw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;link rel=&quot;stylesheet&quot; media=&quot;screen&quot; href=&quot;http://networkrepository.com/assets/css/bootstrap.css&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/responsive.css&quot;&gt;   
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://networkrepository.com/assets/css/style.css&quot;&gt;
        ///
        ///&lt;body&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;div class=&quot;container&quot;&gt;
        ///&lt;div class=&quot;row&quot;&gt;
        ///&lt;div class=&quot;col-md-12&quot;&gt;
        ///&lt;div class=&quot;panel panel-success&quot;&gt;
        ///    &lt;div class=&quot;panel-heading&quot;&gt;
        ///        &lt;h3 class=&quot;panel-title&quot;&gt;&lt;i class=&quot;icon-group icon-large&quot;&gt;&lt;/i&gt; Acknowledgement  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reptilia_tortoise_network_hw1 {
            get {
                return ResourceManager.GetString("reptilia_tortoise_network_hw1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
